name: Check pack tag

on:
  push:
    tags:
      - v*

jobs:
  Check-Sintax:
    runs-on: ubuntu-24.04

    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download tarball
        run: |
          tag=$(git describe --tags --abbrev=0)
          wget https://github.com/loadept/qtheme/archive/refs/tags/${tag}.tar.gz

      - name: Check sha
        run: |
          tag=$(git describe --tags --abbrev=0)
          sha=$(sha512sum $tag.tar.gz | awk '{print $1}')
          sed "s/^sha512sums=('.*')\$/sha512sums=('$sha')/" PKGBUILD
